# Generated by Django 3.1 on 2020-09-01 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSector',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, null=True)),
                ('spiked_dropped', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=30)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ceiling_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('lowest_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('highest_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('booming', models.PositiveIntegerField(default=0)),
                ('busting', models.PositiveIntegerField(default=0)),
                ('suspended', models.PositiveIntegerField(default=0)),
                ('spiked_dropped', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.marketsector')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
